backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Navigation Title", name: "navtitle", widget: "string" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "nav" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "frontpage"
    label: "Frontpage"
    files:
      - label: "Frontpage"
        name: "home"
        file: "pages/home.md"
        slug: "{{slug}}"
        fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Permalink", name: "permalink", widget: "string" }
        - { label: "Navigation Title", name: "navtitle", widget: "string" }
        - { label: "Tags", name: "tags", widget: "hidden", default: "nav" }
        - { label: "Banner tekst", name: "bannertext", widget: "text" }
        - { label: "Venteliste tekst", name: "waitinglist-text", widget: "text" }
        - { label: "Rekritterings tekst", name: "recruitment-text", widget: "text" }
        - { label: "Assistance tekst", name: "assistance-text", widget: "text" }
